### ISSUE TITLE
jterator interface: full path shown for module name

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#101]
In prior versions, the module name was shown at the top of the module pipeline. In the latest release, this has been replaced with the full path.
![screen shot 2017-11-23 at 12 56 38](https://user-images.githubusercontent.com/5407848/33171757-ca0b60ea-d04d-11e7-8ffb-07f4acef929a.png)

**Comment by riccardomurri** [comment]
> In the latest release, this has been replaced with the full path.

...which might actually not be a bad thing: since now multiple directories are searched for modules, it's important to know _which_ module `foobar.py` is being picked up (e.g., assuming you have two like-named modules in your search path).

But I agree it's a UI problem that the font is too large and we should probably show the module name and the the full path as secondary info (e.g., smaller font, grayed out, as a kind of subtitle)

**Comment by riccardomurri** [comment]
Fixed in the latest "master" branch.
