### ISSUE TITLE
TmDeploy: Installing tm_client fails because installation requirements are provided differently

### ISSUE THREAD

**Issue by jluethi** [TissueMAPS/TissueMAPS#155]
When trying to deploy a new TissueMaps instance from commit 882b683bd2253c1031a6e40f9771ca35536ea9e4 (see #154 for reasons to use an older version), the deployment fails during tm_client installation. The reason seems to be that tm_client doesn't have a requirements.txt file, while all the other repositories have it. In this commit (2634a999870d3f82453fa60040427e5ba5c48145), tm_client was added to the list of things to be installed, therefore it seems to look for the requirements.txt file here as well, same as the other parts of tissuemaps.
I started looking into how its dependencies are handled and saw that all the dependencies are given in the setup.py file. It turns out that the other parts of tissueMaps like tm_library have a list of dependencies both in the requirements.txt as well as the setup.py file, so I'm not sure which one is actually used in what case. I suspect that generally setup.py is used, but for deployment via tm_deploy the requirements.txt is used. Could be wrong, but if it's like this, I think we should unify the dependencies to one list, not have two separate ones.

`TASK [compute : Install package {{ item.desc }}] *******************************************************************************************************************************************************
failed: [joel_TissueMaps_Testing-standalone-server-001] (item={u'args': u"-r '/home/tissuemaps/TissueMAPS/tmclient/requirements.txt'", u'desc': u'requirements'}) => {"changed": true, "cmd": "env PYTHONUSERBASE='/home/tissuemaps/.local' pip install --user --no-cache-dir -r '/home/tissuemaps/TissueMAPS/tmclient/requirements.txt'", "delta": "0:00:00.545478", "end": "2018-11-28 13:55:28.957166", "failed": true, "item": {"args": "-r '/home/tissuemaps/TissueMAPS/tmclient/requirements.txt'", "desc": "requirements"}, "rc": 1, "start": "2018-11-28 13:55:28.411688", "stderr": "Could not open requirements file: [Errno 2] No such file or directory: '/home/tissuemaps/TissueMAPS/tmclient/requirements.txt'", "stderr_lines": ["Could not open requirements file: [Errno 2] No such file or directory: '/home/tissuemaps/TissueMAPS/tmclient/requirements.txt'"], "stdout": "", "stdout_lines": []}`

**Comment by riccardomurri** [comment]
I've made the `pip install -r requirements.txt` optional: it only runs if a `requirements.txt` file is actually present.

**Comment by riccardomurri** [comment]
As for duplication of package dependencies in `setup.py` and `requirements.txt`: yes, it's a well-known pain point in Python packaging.  The current consensus is that they serve a slightly different purpose: 

- `setup.py` should list dependent packages at a *minimum compatible* version;
- `requirements.txt` should list dependent packages (and their dependencies, etc) at a *known good* version.

The idea is that you should be able to exactly reproduce a working/development environment by running `pip install -r requirements.txt`, whereas `setup.py install` would grab the latest versions of all compatible packages, which may not work due to dependencies having been updated in incompatible ways.

**Comment by jluethi** [comment]
@riccardomurri Thanks for the clarification & the fix 👍
