### ISSUE TITLE
Cannot see which images have been uploaded

### ISSUE THREAD

**Issue by maffka123** [TissueMAPS/TissueMAPS#22]
When uploading images using command line I cannot see which images were actually loaded

<img width="1169" alt="bildschirmfoto 2017-02-03 um 13 04 39" src="https://cloud.githubusercontent.com/assets/19744910/22590856/a15a15ce-ea11-11e6-8a9b-4b3a0f335b8c.png">

Would be nice if they would be displayed in the web interface or if there would be a command similar to *ls*, so that I could see all the list through my terminal.

That would help to understand what is missing here:

<img width="877" alt="bildschirmfoto 2017-02-03 um 10 11 58" src="https://cloud.githubusercontent.com/assets/19744910/22590896/e926ee04-ea11-11e6-9fa7-362b01e3c6b7.png">

I was 100% sure that all images were loaded.

In addition I wonder is there a way to specify in the command line which images to load. Let's say, I don't want to load all the folder now, but only couple of wells. Is there a way to set the range?

**Comment by HackerMD** [comment]
> When uploading images using command line I cannot see which images were actually loaded

This is because the underlying list of image names is only created client side, using drag&drop for example.

> Would be nice if they would be displayed in the web interface or if there would be a command similar to ls, so that I could see all the list through my terminal.

I agree, this would be nice. We haven't done this so far to avoid pulling all this information from the server (see below).

Generally, it would be nice to have an interface to view the list of images in a kind of pseudo-filesystem and be able to click on individual images to look at them, similar to the dropbox interface.

I've described this feature request in the separate issue #23.

> I was 100% sure that all images were loaded.

This message may appear temporarily despite all images beeing uploaded successfully. This can happen because of the time it takes for the server to send the relevant information to the client, which may take a while for a large dataset. Does "upload" finally get a green check label when waiting a bit longer?

Also note, that there are problems, when switching between experiments (see issue #9).

> In addition I wonder is there a way to specify in the command line which images to load. Let's say, I don't want to load all the folder now, but only couple of wells. Is there a way to set the range?

Not at the moment, but adding this functionality would be easy. If you are interested in this feature, please create a separate issue for it.

**Comment by hackermd** [comment]
You can list all registered files (and see their upload status) using the `tm_client` command line tool:

```
$ tm_cient -H $HOST -u $USER -p $PASSWORD microscope-file ls
```
